//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class energy20 : DbContext
    {
        public energy20()
            : base("name=energy20")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<building> buildings { get; set; }
        public DbSet<company> companies { get; set; }
        public DbSet<diesel> diesels { get; set; }
        public DbSet<electrical> electricals { get; set; }
        public DbSet<energy> energies { get; set; }
        public DbSet<permission> permissions { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<permissionview> permissionviews { get; set; }
    }
}
