//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class energy
    {
        public energy()
        {
            this.permissions = new HashSet<permission>();
        }
    
        public int energy_id { get; set; }
        public string energy_name { get; set; }
        public string energy_detail { get; set; }
    
        public virtual ICollection<permission> permissions { get; set; }
    }
}
