//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class permissionview
    {
        public string name { get; set; }
        public string building_name { get; set; }
        public string energy_name { get; set; }
        public string company_name { get; set; }
        public string building_company_companycode { get; set; }
    }
}
