//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class permission
    {
        public permission()
        {
            this.diesels = new HashSet<diesel>();
            this.electricals = new HashSet<electrical>();
        }
    
        public int user_id { get; set; }
        public int building_buidlingid { get; set; }
        public string building_company_companycode { get; set; }
        public int energy_energy_id { get; set; }
    
        public virtual building building { get; set; }
        public virtual ICollection<diesel> diesels { get; set; }
        public virtual ICollection<electrical> electricals { get; set; }
        public virtual energy energy { get; set; }
        public virtual user user { get; set; }
    }
}
